### ISSUE TITLE
1.20.0

### ISSUE THREAD

**Issue by dandcg** [stackify/stackify-api-dotnet#11]
Updated to 1.20.0 and get null reference error on calling Logger.CanSend()?

Apikey is blank so dev envs don't send to Stackify, framework used for Prefix.

Any guidance?

Dan

**Comment by sporty81** [comment]
@dandcg Do you have a full stack trace of the error?

**Comment by sporty81** [comment]
Are you calling it via StackifyError.SendToStackify() ?

**Comment by dandcg** [comment]
Stack trace is short.... Its actually occurring in the Serilog sink...

https://github.com/jpknoll/Serilog.Sinks.Stackify/blob/master/Serilog.Sinks.Stackify/Sinks/Stackify/StackifySink.cs

But removing that from the equation I'm seeing a null reference error in the Static Logger class if I breakpoint on start-up. Its occurring in the constructor of HttpClient...

**Comment by sporty81** [comment]
I found the problem. Will have a new nuget package soon. Workaround is to add in your appSettings a key for Stackify.Url and set it to https://api.stackify.com/

**Comment by sporty81** [comment]
StackifyLib v1.21 should fix the issue. It is live now. Thanks!

**Comment by dandcg** [comment]
Thanks Matt for an amazingly quick fix.

Sent from my HTC

----- Reply message -----
