### ISSUE TITLE
EnvironmentDetail.GetDeviceName does not support IMDSv2. 

### ISSUE THREAD

**Issue by varun7387** [stackify/stackify-api-dotnet#149]
We recently upgraded our EC2 host instances to use an AL2023 ami image. 
These new images do not support IMDSv1, which the EnvironmentDetail.GetDeviceName leans on to fetch the EC2 instance id. 

This caused us to have a massive rise in our bills from Stackify as every container got marked as a separate host.

IMDSv1 allowed fetching metadata without the need of any tokens.
By default al-2023 images have IMDSv1 disabled. 
IMDSv2 requires a call to be made to `PUT "http://169.254.169.254/latest/api/token"` to fetch a token, which can then used to make calls to the `http://169.254.169.254/latest/metadata` endpoints for fetching metadata.

From AWS:
![image](https://github.com/stackify/stackify-api-dotnet/assets/2689509/dae31a2c-b843-4b40-9f77-d19e808a83d7)

AWS documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-transition-to-version-2.html

For others who come across the issue:
We have had to temporarily allow IMDSv1 on our ECS instances, by marking IMDSv2 optional. 
```
aws ec2 modify-instance-metadata-options \
--instance-id <instance-0123456789example> \
--http-tokens optional \
--http-endpoint enabled
```

**Comment by homiedopie** [comment]
Hi @varun7387 - **StackifyLib 2.2.14** has been released. Let us know if you encounter any problems. 

Link: https://www.nuget.org/packages/StackifyLib/2.2.14
