### ISSUE TITLE
EnvironmentDetail.GetDeviceName check for EC2 environment always runs

### ISSUE THREAD

**Issue by kfsit** [stackify/stackify-api-dotnet#152]
There is a logical error with the check to see if the environment is an EC2 machine.  Because of this, on first run it tries to ping a non existent EC2 server which causes a delay of 30 seconds while waiting for the check to complete.  

In the code snippet below, **any one of the conditions** will allow checking of EC2

1. Config.IsEc2 == null
2. Config.IsEc2 == true
3. isDefaultDeviceNameEc2

Condition 1 is checking if the variable is null - e.g. no value is set.  On loading our configuration, IsEc2 is null, in which case it meets the condition and calls GetEC2InstanceId().  This call will eventually fail but require waiting for 20-30 seconds while it tries to connect to Ec2.  

The condition could be written as `if ((Config.IsEc2.HasValue && Config.IsEc2) || isDefaultDeviceNameEc2)`

Note, that after the first run the values are cached so no further attempts at connecting with Ec2 is made.

![image](https://github.com/stackify/stackify-api-dotnet/assets/1545364/bc7279ec-d35d-47c4-8a21-8006cb69ad89)

**Comment by t-lair** [comment]
@kfsit can you confirm this PR addresses your concerns? https://github.com/stackify/stackify-api-dotnet/pull/153

**Comment by homiedopie** [comment]
@kfsit  - The package is already available as `2.2.15-beta`  - Let me know if you have questions

Link: https://www.nuget.org/packages/StackifyLib/2.2.15-beta
