### ISSUE TITLE
No stack trace with Log4Net Remoting Appender

### ISSUE THREAD

**Issue by ronin1** [stackify/stackify-api-dotnet#22]
We are using Log4net (1.2.13) with the Remoting Appender and we are not getting any stack trace in stackify for our errors (it shows an empty array in the UI).

We traced it to this line of your code: https://github.com/stackify/stackify-api-dotnet/blob/master/Src/StackifyLib.log4net/StackifyAppender.cs#L150#

Would it be possible to have fall back logic that extracts the frame from the passed in loggingEvent instead of the current stack (which is not available because the error exists on a different machine & is sent over via remoting).

We have some old services that are using the log4net remoting appender and the error logs are not helpful without the stack trace.

**Comment by sporty81** [comment]
If you disable the remoting appender and only use the StackifyAppender does it then work correctly with Stackify?

**Comment by sporty81** [comment]
Is your code logging an actual Exception object or just a string? If you aren't, that would explain it. 

The code that actually builds the frames is here:
https://github.com/stackify/stackify-api-dotnet/blob/master/Src/StackifyLib/Models/ErrorItem.cs#L117

**Comment by ronin1** [comment]
It’s an actual exception (we have a throw test). It’s only because the exception didn’t happen in the same context of the logger, it happened on another machine & then sent over via remoting.

On Nov 2, 2016, at 7:13 PM, Matt Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


Is your code logging an actual Exception object or just a string? If you aren't, that would explain it.

The code that actually builds the frames is here:
https://github.com/stackify/stackify-api-dotnet/blob/master/Src/StackifyLib/Models/ErrorItem.cs#L117

**Comment by sporty81** [comment]
Ok, never heard of anyone doing that before. I will see if there is anything we can do to fix it.

**Comment by ronin1** [comment]
Thank you
