### ISSUE TITLE
Problems building

### ISSUE THREAD

**Issue by evest** [stackify/stackify-api-dotnet#23]
I'm having some problems building the projects in the solution (from master). Especially the main `StackifyLib` which seems to have both 4.0, 4.5 and Core configuration in it.

After having removed the missing monitors.cs, project.json, the xproj, added the missing /utils/EtwEventListener.cs, added NET45 conditional AND set the target framework to 4.6 I was able to build it.

I wanted to do the right thing, and create a PR for more information in the `WebRequestDetail` but this whole ordeal makes me wonder if I'm really supposed to make this work off your current codebase, or if I should just suggest the feature to your support.

**Comment by sporty81** [comment]
Use StackifyLibCore.sln - I will delete the old solution file. That was from before switching to core.

**Comment by evest** [comment]
Well, that was embarrassing. Didn't even think of trying that other solution file (assumed it was for dotnet core.)

Thanks a lot. Simple pull request sent, be gentle :-)
