### ISSUE TITLE
System.Web required?

### ISSUE THREAD

**Issue by stevengopmo** [stackify/stackify-api-dotnet#28]
Is System.Web really required for the Api lib?  There are multitudes of ways to make remote calls, interact with IIS, etc. that don't require this dll.

**Comment by sporty81** [comment]
For .NET 4.5 yes it is required to get details about the current web request.

For .NET Core it was split out in to its own package: https://www.nuget.org/packages/StackifyLib.AspNetCore/2.0.0-beta1

What are you trying to do that would not allow you to use System.Web?

**Comment by stevengopmo** [comment]
It is less a case of not allowed and more a case of don't want. We use
Webapi and Owin and have managed to avoid it.  Using System.Web ties us to
Web hosting. What about Windows service?

On Mar 7, 2017 21:05, "Matt Watson" <notifications@github.com> wrote:

For .NET 4.5 yes it is required to get details about the current web
request.

For .NET Core it was split out in to its own package: https://www.nuget.org/
packages/StackifyLib.AspNetCore/2.0.0-beta1

What are you trying to do that would not allow you to use System.Web?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stackify/stackify-api-dotnet/issues/28#issuecomment-284923445>,
or mute the thread

**Comment by stevengopmo** [comment]
Allow me to clarify my previous response.

All we are trying to do here is use Stackify to capture our logs (via Serilog).  We have both a windows service as well as a WebApi (2.2) application.  In neither case does it make sense (to me at least) to require System.Web to call an http endpoint to leave a log.  Although you could make the case for a web app, why is it required for a windows service to take a dependency on System.Web.  It will cloud the service AND since there won't be an HTTPContext it will probably cause errors.

**Comment by sporty81** [comment]
The library looks at System.HttpContext.Current to see if there is a current web request. It won't cause any errors.

It all comes down to ease of use and keeping things simple. I played with the idea this morning of making a StackifyLib.NoWeb version and the problem then becomes having to make a Serilog version that references that one instead. Perhaps some hackery with assembly binding redirects could workaround this.... I don't know. Back to keeping it simple!

You are more than welcome to fork StackifyLib and our Serilog packages if you would like, but for now we will keep them as is. System.Web is required... but shouldn't hurt anything.

**For .NET Core, we have done what you are looking for.**

**Comment by sporty81** [comment]
P.S. It also has a reference to System.Management which you also don't need. It is just the nature of trying to make a 3rd party library that supports multiple use cases.

**Comment by Matthew-Bonner** [comment]
It is now almost August, is there an update for this as we are also migrating to .NET Core.

**Comment by strvmarv** [comment]
Apologies, but System.Web will remain in the non-core targeted version of the package.  .NET Core packages have been released.
