### ISSUE TITLE
Refactor Logger to avoid static methods and remove need to call Shutdown method

### ISSUE THREAD

**Issue by Matthew-Bonner** [stackify/stackify-api-dotnet#31]
Instead of requiring the call `StackifyLib.Logger.Shutdown();` can't you use a singleton pattern like so:

ILogger logger = StackifyLib.Logger.Current; // Creates a new logger instance if one is not created.

So...
```
StackifyLib.Logger.Queue("DEBUG", "My log message");
StackifyLib.Logger.QueueException("Test exception", new ApplicationException("Sky is falling"));
```

Becomes...
```
StackifyLib.Logger.Current.Queue("DEBUG", "My log message");
StackifyLib.Logger.Current.QueueException("Test exception", new ApplicationException("Sky is falling"));
```

And then use the destructor to persist queued logs.

This way you can have multiple loggers and you can remove all the static method calls, making the class unit testable.

The change suggested is backwards compatible too with the existing API.

**Comment by sporty81** [comment]
Well, we don't recommend using StackifyLib's logger directly. 

It is recommended to use NLog, Serilog, or log4net so you can easily point your logging at various outputs. 

For those, they also require calling shutdown on them to close them properly.
            NLog.LogManager.Shutdown();
            log4net.LogManager.Shutdown();
            Serilog.Log.CloseAndFlush();

So based on that, I don't think we should make any changes.

**Comment by Matthew-Bonner** [comment]
Hi Matt

Not sure if you are aware but there is an example on your website which promotes using the StackifyLib directly and there is no mention on the page that it isn't recommended to do so:
http://support.stackify.com/hc/en-us/articles/205419565-Stackify-API-for-NET

This is where I started when looking into implementing logging to Stackify.

Not sure if you think it is worth putting some additional information on that page to mention what you have said as some may get confused over what the recommended method is after seeing this information.

Thanks,
Matt
