### ISSUE TITLE
StackifyLib is unsigned

### ISSUE THREAD

**Issue by j0ales** [stackify/stackify-api-dotnet#32]
Why is StackifyLib unsigned?

**Comment by Matthew-Bonner** [comment]
Having an abstract notion of version and baking in signature detection seems like a harder way to deal with things.

**Comment by Inversebit** [comment]
This also did cause a problem for me. Because of the stackify assemblies being unsigned, I cannot use them in my signed .NET project.

It's not a major problem, because one can download the repo and compile a self-signed version, but having signed DLLs from the original developer would be nice.

**Comment by j0ales** [comment]
StackifyLib.log4net is signed

**Comment by eric-martin** [comment]
Out current workaround for this is what @Inversebit suggested. Download and compile a self-signed version.
