### ISSUE TITLE
Serilog Prefix Logging Problem - Unable to find an entry point named 'GetSystemTimePreciseAsFileTime' in DLL 'Kernel32.dll'

### ISSUE THREAD

**Issue by ritwikroy7** [stackify/stackify-api-dotnet#39]
I'm using Serilog with Serilog.Sinks.Stackify to try and log to Prefix from my WCF application. I'm doing this on a Windows 7 machine running .NET 4.6.1 on VS2015.

From what I can find it seems 'GetSystemTimePreciseAsFileTime' is not available on Windows 8 and below.

Is there any possible fix other than moving to a newer version of Windows?

Thanks,
Ritwik

**Comment by strvmarv** [comment]
It appears you are correct.  Apologies, we'll see about getting this fixed.

**Comment by ritwikroy7** [comment]
Thank you for looking into it.

**Comment by strvmarv** [comment]
Interesting, the only old vm I have handy is Win2k8, which does not support this function as well.  Yet the fall-back logic does indeed work and doesn't let the exception bubble higher in the stack.  It will throw, but should be caught.  Are you debugging when this occurs?  Are you using break on all exceptions or something along those lines?

**Comment by strvmarv** [comment]
So the actual issue is a log isn't being written to Prefix...ok, thanks...
