### ISSUE TITLE
StackifyLib NuGet packaging issue for .NET Framework 4.5.1

### ISSUE THREAD

**Issue by mmiller678** [stackify/stackify-api-dotnet#48]
https://www.nuget.org/packages/StackifyLib/

The nuget package for version StackifyLib 2.0 for .NET Framework 4.5.1 is requiring package Microsoft.Extensions.Configuration.  I don't believe this is correct given this package is for .NET Standard not the .NET Framework.  Can you please adjust this and re-publish to NuGet so we can pull in this library.

**Comment by strvmarv** [comment]
There's nothing wrong with using that package on FF as long as the framework version implements the correct Net standard version.

For example, I can run AspNetCore web apps on FF. They require this package as well.

**Comment by mmiller678** [comment]
I think the issue is it pulls in a lot of additional dependencies which in turn get pulled into our projects and configurations.  Is this behavior you were hoping introduce?  

![image](https://user-images.githubusercontent.com/3980108/29420520-2dc327fe-8340-11e7-9a3b-3a644ebe0f90.png)

**Comment by jaredcnance** [comment]
This is an issue many libraries will face as they move to support netstandard and dotnet core applications. This is because [Microsoft.Extensions.Configuration 1.1.1](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/1.1.1) brings in the `NETStandard.Library`. But, when you actually build, there will be no additional DLLs (types are forwarded to the net451 types in the GAC)  to and therefore should have no runtime affect on your application.

The good news is that if we decide to target netstandard 2.0 this bloat will go away.

**Comment by mmiller678** [comment]
Thanks for the quick response.  We haven't seen this with any other 3rd party libraries we are using that are targeting .NET standard so I found this to be surprising.   Is there a set of release notes for what changed moving to 1.25.4 to 2.0 so we can evaluate if this is even something we need to upgrade?  Also do you have a time frame in mind for moving to .NET Standard 2.0 to avoid this? We have a lot of libraries that depend on our internal logging library which uses Stackify and while like you said it shouldn't affect anything I think it would require some testing on our part to get this deployed.

**Comment by strvmarv** [comment]
- .NET Core Support (targeting NETStandard 1.3)
- Enhancements around GetEC2InstanceId, especially when not using AWS

You can find the commits for StackifyLib 2.0 here...

https://github.com/stackify/stackify-api-dotnet/commit/88e673c1120fcc1e60479edb77bde8bd68ce6539

The dependencies pulled appear relatively benign, but I'm not familiar with your stack, so I'll leave it at that.  As for .NET Standard 2.0, it was released only a few days ago and I do not have any time-frame to provide at this time.  If you are not experiencing issues with StackifyLib 1.25.4 and not using dotnet core, this upgrade is not required.
