### ISSUE TITLE
NLog target does not capture Properties

### ISSUE THREAD

**Issue by JonCubed** [stackify/stackify-api-dotnet#56]
NLog has [Event Properties](https://github.com/nlog/nlog/wiki/EventProperties-Layout-Renderer) which is used for logging custom values. 

```c#
LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Pass my custom value");
theEvent.Properties.Add("MyValue", "My custom string");
theEvent.Properties.Add("MyDateTimeValue", new DateTime(2015, 08, 30, 11, 26, 50));
logger.Log(theEvent);
```

Currently the NLog target does not capture these values and it would be very nice if it could.

a naive fix would be adding something like below 

```csharp
if (loggingEvent.Properties.Any())
{
    // capture properties of log event
   loggingEvent
         .Properties
         .ToList()
         .ForEach(prop => diags.Add(prop.Key.ToString(), prop.Value));
 }
```
after 
https://github.com/stackify/stackify-api-dotnet/blob/ed40f4c7e09418f135ef3bea01c07b27cdeec055/Src/NLog.Targets.Stackify/StackifyTarget.cs#L296-L301

**Comment by JonCubed** [comment]
I'm happy to provide a PR if required

**Comment by strvmarv** [comment]
A PR would be appreciated, thanks!

**Comment by snakefoot** [comment]
@JonCubed Nuget-package here: https://www.nuget.org/packages/NLog.Targets.Stackify/2.0.2
