### ISSUE TITLE
Wrong server name on .net core

### ISSUE THREAD

**Issue by Zeroto** [stackify/stackify-api-dotnet#63]
When using NLog.Target.Stackify then the reported server name is always `.`. This seems to be caused by the following line:  https://github.com/stackify/stackify-api-dotnet/blob/06a20bf70a1cf7b45ea5876dfe88362970e488f6/Src/StackifyLib/Models/EnvironmentDetail.cs#L192

The documentation of Process.MachineName has the following note: `When the associated process is executing on the local machine, this property returns a period (".") for the machine name`
This would mean that this line will always return `.` because the current process will always be running on the local machine.

**Comment by strvmarv** [comment]
Thanks for the heads-up, I'll get it added to our next cycle.  In the meantime, feel free to submit a PR if you're up for it...

**Comment by strvmarv** [comment]
Appears Environment.MachineName is fully supported now, will swap it out...
