### ISSUE TITLE
ASP.NET Core 2 support - ILoggingBuilder extension

### ISSUE THREAD

**Issue by Matthew-Bonner** [stackify/stackify-api-dotnet#66]
Are there any plans to support an ILoggingBuilder extension method along the lines of something like ILoggingBuilder.AddStackifyLib(); so that we can configure logging in our Program class rather than in the IStartup.Configure method?

**Comment by strvmarv** [comment]
Not at this time, but we will certainly keep this in mind as we continue forward with Core 2 support...
