### ISSUE TITLE
App crash with ASP.NET Core

### ISSUE THREAD

**Issue by Matthew-Bonner** [stackify/stackify-api-dotnet#69]
We keep getting crashes when running our new ASP.NET Core app.

Steps to reproduce:
1. Publish website
2. Make a few requests
3. Leave the website with no requests for a minute or so
4. The app crashes

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	dotnet.exe
  Application Version:	2.0.26021.1
  Application Timestamp:	5a3b026e
  Fault Module Name:	StackifyProfiler_x64.dll
  Fault Module Version:	4.0.6.9
  Fault Module Timestamp:	59f0cdeb
  Exception Code:	c0000005
  Exception Offset:	000000000005f693
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	ae86
  Additional Information 2:	ae860a156c9d9ef453b0254d4be3fd76
  Additional Information 3:	d4ae
  Additional Information 4:	d4ae15ddac055b140b0e91f6e26a9d03

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: dotnet.exe
P2: 2.0.26021.1
P3: 5a3b026e
P4: StackifyProfiler_x64.dll
P5: 4.0.6.9
P6: 59f0cdeb
P7: c0000005
P8: 000000000005f693
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\MatthewB\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_dotnet.exe_e291691d7b62f9c3b374c4617a4eebfa6b124ad_1c88e72c

Analysis symbol: 
Rechecking for solution: 0
Report Id: effaf68b-195f-11e8-939b-005056c00008
Report Status: 0

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Version=1
EventType=APPCRASH
EventTime=131639496483989411
ReportType=2
Consent=1
ReportIdentifier=effaf68c-195f-11e8-939b-005056c00008
IntegratorReportIdentifier=effaf68b-195f-11e8-939b-005056c00008
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=dotnet.exe
Sig[1].Name=Application Version
Sig[1].Value=2.0.26021.1
Sig[2].Name=Application Timestamp
Sig[2].Value=5a3b026e
Sig[3].Name=Fault Module Name
Sig[3].Value=StackifyProfiler_x64.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=4.0.6.9
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=59f0cdeb
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000005f693
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=2057
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=ae86
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=ae860a156c9d9ef453b0254d4be3fd76
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=d4ae
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=d4ae15ddac055b140b0e91f6e26a9d03
UI[2]=C:\Program Files\dotnet\dotnet.exe
UI[3]=dotnet has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\dotnet\dotnet.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\SYSFER.DLL
LoadedModule[5]=C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[6]=C:\Windows\system32\ucrtbase.DLL
LoadedModule[7]=C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
LoadedModule[8]=C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll
LoadedModule[9]=C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll
LoadedModule[10]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
LoadedModule[11]=C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
LoadedModule[12]=C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll
LoadedModule[13]=C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[14]=C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[15]=C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[16]=C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[17]=C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[18]=C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[19]=C:\Windows\system32\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[20]=C:\Program Files\dotnet\host\fxr\2.0.5\hostfxr.dll
LoadedModule[21]=C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[22]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\hostpolicy.dll
LoadedModule[23]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\coreclr.dll
LoadedModule[24]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[25]=C:\Windows\system32\msvcrt.dll
LoadedModule[26]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[27]=C:\Windows\system32\RPCRT4.dll
LoadedModule[28]=C:\Windows\system32\ole32.dll
LoadedModule[29]=C:\Windows\system32\GDI32.dll
LoadedModule[30]=C:\Windows\system32\USER32.dll
LoadedModule[31]=C:\Windows\system32\LPK.dll
LoadedModule[32]=C:\Windows\system32\USP10.dll
LoadedModule[33]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[34]=C:\Windows\system32\VERSION.dll
LoadedModule[35]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[36]=C:\Windows\system32\bcrypt.dll
LoadedModule[37]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[38]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[39]=C:\Windows\system32\IMM32.DLL
LoadedModule[40]=C:\Windows\system32\MSCTF.dll
LoadedModule[41]=C:\Program Files (x86)\Stackify\Profiler\v4.0.6.9\x64\StackifyProfiler_x64.dll
LoadedModule[42]=C:\Program Files (x86)\Stackify\Profiler\v4.0.6.9\x64\cpprest120_2_8.dll
LoadedModule[43]=C:\Windows\system32\WINHTTP.dll
LoadedModule[44]=C:\Windows\system32\webio.dll
LoadedModule[45]=C:\Windows\system32\HTTPAPI.dll
LoadedModule[46]=C:\Windows\system32\CRYPT32.dll
LoadedModule[47]=C:\Windows\system32\MSASN1.dll
LoadedModule[48]=C:\Windows\system32\MSVCP120.dll
LoadedModule[49]=C:\Windows\system32\MSVCR120.dll
LoadedModule[50]=C:\Windows\system32\WS2_32.dll
LoadedModule[51]=C:\Windows\system32\NSI.dll
LoadedModule[52]=C:\Windows\system32\SHELL32.dll
LoadedModule[53]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Private.CoreLib.dll
LoadedModule[54]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[55]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\clrjit.dll
LoadedModule[56]=C:\Users\MatthewB\my documents\visual studio 2017\Projects\MVC\Ev.Web.UI.ImageServer.Benchmark\bin\Release\netcoreapp2.0\Ev.Web.UI.ImageServer.Benchmark.dll
LoadedModule[57]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Runtime.dll
LoadedModule[58]=C:\Users\MatthewB\.nuget\packages\benchmarkdotnet.core\0.10.12\lib\netcoreapp2.0\BenchmarkDotNet.Core.dll
LoadedModule[59]=C:\Users\MatthewB\my documents\visual studio 2017\Projects\MVC\Ev.Web.UI.ImageServer.Benchmark\bin\Release\netcoreapp2.0\Ev.Generic.Benchmark.dll
LoadedModule[60]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Console.dll
LoadedModule[61]=C:\Users\MatthewB\.nuget\packages\benchmarkdotnet\0.10.12\lib\netcoreapp2.0\BenchmarkDotNet.dll
LoadedModule[62]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Linq.dll
LoadedModule[63]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Collections.dll
LoadedModule[64]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Runtime.Extensions.dll
LoadedModule[65]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Linq.Expressions.dll
LoadedModule[66]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Threading.dll
LoadedModule[67]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Collections.Concurrent.dll
LoadedModule[68]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.IO.FileSystem.dll
LoadedModule[69]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[70]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Runtime.InteropServices.dll
LoadedModule[71]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Xml.ReaderWriter.dll
LoadedModule[72]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Private.Xml.dll
LoadedModule[73]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[74]=C:\Windows\system32\rsaenh.dll
LoadedModule[75]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Private.Uri.dll
LoadedModule[76]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Net.Primitives.dll
LoadedModule[77]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Text.Encoding.Extensions.dll
LoadedModule[78]=C:\Users\MatthewB\.nuget\packages\microsoft.aspnetcore.testhost\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.TestHost.dll
LoadedModule[79]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\netstandard.dll
LoadedModule[80]=C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.hosting.server.abstractions\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
LoadedModule[81]=C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.aspnetcore.http.features\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=dotnet
AppPath=C:\Program Files\dotnet\dotnet.exe

**Comment by eric-martin** [comment]
This doesn't appear to be related to the stackify-api-dotnet project. I'll get a support ticket opened up for you.
