### ISSUE TITLE
Make ProfileTracer support non-wrapped calls for Azure WebJobs

### ISSUE THREAD

**Issue by dmarlow** [stackify/stackify-api-dotnet#70]
I'd like to trace azure webjobs without littering my code such that every single WebJob function has a `tracer.Exec(() => ...)` call. Is there any way to properly use the Stackify ProfileTracer with the WebJobs function filter? 

https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters

Basically, we need some way to "begin" and "end" a timing session without explicitly wrapping or passing the `Action`.

**Comment by eric-martin** [comment]
We will keep our eye on this. Once it is out of preview, we will evaluate.

**Comment by dmarlow** [comment]
I'm now coming back to this and am curious if I use the function filter I mentioned above, but use Metrics if I could achieve the same result. Where would the metrics show up if they were used?

**Comment by mattjbrooksii** [comment]
I would imagine that you could if all you are looking to do is time a method. Custom Metrics show up under application monitors. See this doc site for more info: https://docs.stackify.com/docs/app-monitors-overview and https://stackify.com/use-custom-application-metrics/

Click into your webapp > monitoring tab > Environment dropdown > Server drop down

If you have anymore questions or concern feel free to reach out to us at https://support.stackify.com/submit-a-ticket/ that way we can guarantee better customer support.
