### ISSUE TITLE
Why didn't you separate the packages?

### ISSUE THREAD

**Issue by tsfinley** [stackify/stackify-api-dotnet#74]
The .NET Standard requirement on a project that does not use nor does my hosting environment support. Due to this requirement of your nuget package, I have added a boat load of packages I do not need nor have time to test to ensure it did not inject new errors. 

Please break up the NuGet packages. I'm downloading your package and am just going to include the DLL I require.

**Comment by strvmarv** [comment]
.NET Standard is the target for the future and we support it.  Specifically .NET Standard 2.0 which coordinates with .NET Full Framework version 4.6.1.  Running parallel packages is/should be unnecessary, which is the point.  Framework level types should forward to their full framework equivalent on build and eliminate most of the "bloat" you see in nuget.  It is what it is...

See this issue for more details...

https://github.com/stackify/stackify-api-dotnet/issues/48
