### ISSUE TITLE
Need support of MappedDiagnosticsLogicalContext instead of CallContext

### ISSUE THREAD

**Issue by suchil1850** [stackify/stackify-api-dotnet#75]
.Net core does not have support for CallContext. So we are unable to use MDLC feature (MappedDiagnosticsLogicalContext) provided by NLog. As most of the core apps use async extensively, can you pls add support for MappedDiagnosticsLogicalContext in StackifyTarget class. This way we can setup transid in mappedContextKeys attribute for stackify target inside nlog config. This will allow to set our cutsom transid value in stackify. The value of transid key = HttpContext.TraceIdentifier.

Also we need the ability to mask sensitive data in certain fields of LogMsg object. The fields that need masking are Msg, data, and Ex.Message. Can you pls mark Translate method in StackifyTarget class as virtual so that we can override in derived class and in our overridden method we will first call base class method and then apply masking in LogMsg object returned by the base method. Then overidden method will return masked LogMsg object.

**Comment by snakefoot** [comment]
Created PR #83
