### ISSUE TITLE
RequestTracerMiddleware Sending 200 response when Exception thrown

### ISSUE THREAD

**Issue by Skylertodd** [stackify/stackify-api-dotnet#76]
It seems that if you add the Stackify Dotnet Core middleware into your application pipeline it will override a server exception and return it as a 200 response code.  As you can imagine, this can cause some issues when dealing with an API.  

To reproduce this fire up any MVC application and configure it to use StackifyMiddleware.  Once you do that in any controller configure the action to throw and exception.  From the client, even though the exception is thrown, a 200 is received.

Startup Configure
` public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {            
            app.UseStackifyMiddleware();
            app.UseMvc();
        }`

Controller Action 
`     public async Task<ActionResult<IEnumerable<string>>> Get()
        {
            throw new SystemException();
        }`

Since it doesnt appear the UseStackifyMiddleware is open source, I figured this to be the next best place to get a comment on this issue with this product.  If there is a better way to get support, please let me know.

**Comment by mattjbrooksii** [comment]
Thanks for reporting this issue. Normally this type of request would be submitted on our support site https://support.stackify.com/submit-a-ticket/ so if you have any further questions or concerns feel free to reach out.

We will be looking into your issue momentarily.

**Comment by Skylertodd** [comment]
Just an update, I've found that if you place an `app.UseExceptionHandler();` between UseStackifyMiddleware and UseMvc it seems to resolve the exception presenting 200 behavior, I'm curious if this is a good idea, or if it will obscure some of the middlware's perspective of the application.

**Comment by Skylertodd** [comment]
Just got a response from stackify support.  


> Thanks for reaching out to Stackify.
> 
> Changing the order of app.UseMiddleware<StackifyMiddlewre.RequestTracerMiddleware>();to be above app.UseExceptionHandler()should fix the issue.
> In term of whether it will obscure the middleware, we have already tested this and everything looks to be excepted.
> 
> I will notify our team to have the documents updated so this will remove any confusion in the future.
>

**Comment by waynebrantley** [comment]
Not sure where source is for RequestTracerMiddlware?
Decompilation shows the catch of every exception.  @mattjbrooksii can we get this fixed?  I had to disable stackify on all netcore projects.
```
Stream originalBodyStream = context.Response.Body;
          HttpContext httpContext = context.Response.HttpContext;
          try
          {
            RequestTracerMiddlewareOptions middlewareOptions = new RequestTracerMiddlewareOptions()
            {
              ShouldCollect = this._moduleSettings.CollectResponse,
              ShouldInject = this._moduleSettings.CollectClientStats,
              InjectScriptHost = this._moduleSettings.ClientScriptHost,
              InjectScriptSource = this._moduleSettings.ClientScriptSource,
              IsPrefix = this._moduleSettings.IsPrefix,
              MaxCollectBytes = this._moduleSettings.CollectResponseMaxLength,
              StackifyAppName = this._moduleSettings.StackifyAppName,
              StackifyEnvName = this._moduleSettings.StackifyEnvSetting
            };
            context.Response.Body = (Stream) ShadowStreamFactory.Create(identifier, httpContext, originalBodyStream, (IShadowStreamOptions) middlewareOptions);
            await this._next(context);
          }
          catch
          {
          }
          finally
          {
            this.DoRequestEnded(context, traceIdentifier, identifier);
            context.Response.Body = originalBodyStream;
          }
```

**Comment by mattjbrooksii** [comment]
@waynebrantley We have this fix planned for the next release of our middleware. Our middleware is not open source. Thank you for your diligence.

**Comment by strvmarv** [comment]
This is not related to stackify-api-dotnet.  Please utilize the suggested communication channel.

**Comment by waynebrantley** [comment]
@mattjbrooksii Thanks - can you advise me when this is released.
