### ISSUE TITLE
Configuring proxy with .NetCore2.1

### ISSUE THREAD

**Issue by mesterkg** [stackify/stackify-api-dotnet#81]
I'm trying to use stackifyLib from behind a proxy. The docs tells me it's easy, and here is what I'm trying:
```
var stackify = config.GetSection("Stackify");
Config.ApiKey = stackify["ApiKey"];
Config.AppName = stackify["AppName"];
Config.Environment = stackify["Environment"];

var webProxy = new WebProxy(new Uri("http://proxy:8888"))
{
     UseDefaultCredentials = true,
     BypassProxyOnLocal = false
};
StackifyLib.Utils.HttpClient.CustomWebProxy = webProxy;
```

This doesn't work, and after some troubleshooting, I check out the StackifyLib source were I find that the CustomWebProxy is only ever used in .NETFULL.

Is this intentional? Is there another way I'm supposed to setup proxy when using .netcore2.1?

Any help appreciated!

kind regards,
Kjetil

**Comment by snakefoot** [comment]
Guess the HttpClient needs to be created with a [HttpClientHandler](https://docs.microsoft.com/dotnet/api/system.net.http.httpclienthandler):

```c#
var handler = new HttpClientHandler();
handler.Proxy = webProxy;
handler.UseProxy = true;
var httpClient = new HttpClient(handler);
```

See also https://github.com/dotnet/corefx/issues/28780#issuecomment-378322214

**Comment by snakefoot** [comment]
Maybe you are lucky and this will help if called before using stackify-lib:

`System.Net.WebRequest.DefaultWebProxy = webProxy;`

**Comment by mesterkg** [comment]
> Maybe you are lucky and this will help if called before using stackify-lib:
> `System.Net.WebRequest.DefaultWebProxy = webProxy;`

Thank you for the responses. I ended up setting the WebRequest's DefaultWebProxy.

--kg
