### ISSUE TITLE
What does #errorgoverned do?

### ISSUE THREAD

**Issue by jzabroski** [stackify/stackify-api-dotnet#87]
https://github.com/stackify/stackify-api-dotnet/blob/d601def6458e7bdfd1286140de6098f7f22dc32c/Src/StackifyLib.log4net/StackifyAppender.cs#L277

I saw this pop up in my log searches recently.  I can't understand under what conditions a stack trace / exception would cause this to be added.  The code above this hash tag insert seems kind of convoluted.  What's the user story in order to help me understand what I'm seeing?

**Comment by mattjbrooksii** [comment]
That tag means a particular error is throwing too many times per minute and the tag truncates it with that message.
This will only happen when the errors are the same as ones previously within the same minute.

If you have any further questions please submit a ticket to us so we can guarantee quality customer service for you. https://support.stackify.com/submit-a-ticket/

**Comment by jzabroski** [comment]
I created support request #38499 for this, as I still think there is nowhere this is documented (at least until this GitHub issue gets indexed by google)
