### ISSUE TITLE
LogicalThreadContext items not showing up in json contextObject for aspnet core apps

### ISSUE THREAD

**Issue by dmarlow** [stackify/stackify-api-dotnet#89]
We're using log4net and have ASP.NET MVC 5 on .NET 4.7.1 and aspnet core 2.2.

The aspnet core app doesn't have any json contextObject properties. The .NET 4.7.1 app works just fine. We're using StackifyLib.log4net 2.1.0. 

Is there a way to diagnose or a sample app to reference to make sure we're setup correctly?

**Comment by mattjbrooksii** [comment]
@dmarlow Currently only the .Net FullFramework build of StackifyLib supports log4net.ThreadLogicalContext as there is a breaking change in the api for getting the CallContext in .Net Core.

I will create a work item for us to add this functionality to .Net Core build of StackifyLib

**Comment by wunki** [comment]
@mattjbrooksii are you able to give us an ETA for this?

**Comment by mattjbrooksii** [comment]
@wunki I can't say for certain as we have a few client issues we are working on at the moment. But my goal is to get a working fix sometime next week. Depending on the complexity, this is subject to change.

Thank you for your patience and understanding

**Comment by mattjbrooksii** [comment]
@dmarlow Would you be willing to provide a sample of the contextObject properties you are trying to use in your project?

This will help me confirm my tests.

**Comment by wunki** [comment]
Hi @mattjbrooksii, this is how we set some logging context currently:

```csharp
log4net.LogicalThreadContext.Properties["user-id"] = "foo";
```

```csharp
var appender = new StackifyAppender()
            {
                Threshold = Level.All,
                Name = "StackifyAppender",
                logicalThreadContextKeys = "user-id",
                globalContextKeys = "pid"
            };
```

We add the logging context through a custom filter:

```csharp
services.AddMvc(config => {
    config.Filters.Add(new AuthLoggingFilter());
});
```

Let me know if you need to know anything else. Thank you!

**Comment by wunki** [comment]
@mattjbrooksii any updates on the above?

**Comment by mattjbrooksii** [comment]
@wunki StackifyLib.log4net 2.1.5 is now available. Please update your version as soon as you can and let me know if you have anymore issues.

**Comment by mattjbrooksii** [comment]
Going to mark this as closed as the issue has been fixed and deployed. If you are still having issues or have any other concerns feel free to make a new issue.

Cheers!

**Comment by wunki** [comment]
Thank you for quickly resolving this. It's running in production for us and working as expected. 🙏
