### ISSUE TITLE
Move NLog config in seperate package

### ISSUE THREAD

**Issue by DavidDeSloovere** [stackify/stackify-api-dotnet#9]
The Stackify.nLog package automatically updates the config to add nlog config node.
But if you already have an nlog.config file, that one just gets ignored.
What happens next is that you run your application and think nlog is broken because all the configuration that you put in nlog.config is ignored. Just wasted half an our trying to figure this out.

I think it would be a better user experience if the NLog configuration was moved to into a seperate Stackify.nLog.Configuration package. You can add a readme to the initial package with information about the configuration.

**Comment by sporty81** [comment]
Depending on how people use NLog there are 2-3 scenarios on how they can do the config. We do understand that. But the good news is that if people have any issues a quick "diff" via source control would show what exact changes happened to help roll back and fix any potential problems, like those that you saw. We appreciate the feedback and will take it in to consideration. Thanks!

**Comment by DavidDeSloovere** [comment]
Sure, a quick diff shows what happened. But that's not the first thing you think of. 
The first thing I thought was: Stackify broke NLog. Let's start debugging if it's a problem with version 4 of NLog or something else.

I suggest that the least you could do, is add a [readme that gets displayed on install](https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-displaying-a-readme.txt-file-during-package-installation), that informs the user that app.config or web.config has been changed, if you choose to keep this strategy that is.
